from django.contrib import admin
from CMSGuias.apps.home import models

admin.site.register(models.Almacene)
admin.site.register(models.Cliente)
admin.site.register(models.Conductore)
admin.site.register(models.Departamento)
admin.site.register(models.Distrito)
admin.site.register(models.Materiale)
admin.site.register(models.userProfile)
admin.site.register(models.Pais)
admin.site.register(models.Provincia)
admin.site.register(models.Transportista)
admin.site.register(models.Transporte)
admin.site.register(models.Unidade)
admin.site.register(models.Brand)
admin.site.register(models.Model)
admin.site.register(models.BrandMaterial)
admin.site.register(models.Cargo)
admin.site.register(models.Herramientas)
admin.site.register(models.Documentos)
admin.site.register(models.FormaPago)
admin.site.register(models.Moneda)
admin.site.register(models.TipoCambio)
admin.site.register(models.Proveedor)
admin.site.register(models.Configuracion)
admin.site.register(models.Employee)
admin.site.register(models.GroupMaterials)
admin.site.register(models.DetailsGroup)
admin.site.register(models.TypeGroup)
admin.site.register(models.Company)