// Generated by CoffeeScript 1.7.1
var calcPriceEdit, calcamounts, changeMaterials, choicePrice;

$(document).ready(function() {
  $(".btn-refresh-price").on("click", calcPriceEdit);
  $("input[name=select]").on("change", changeMaterials);
  $(".btn-purchase").on("click", choicePrice);
  calcamounts();
});

calcamounts = function(event) {
  $("input[name=suppliers]").each(function(index, supplier) {
    var amount, igv, total;
    amount = 0;
    $("input[name=edit" + supplier.value + "]").each(function(index, input) {
      amount += parseFloat(input.getAttribute("data-amount"));
    });
    $(".amount" + supplier.value).html(amount.toFixed(2));
    igv = amount * (parseFloat($("input[name=igv]").val()) / 100);
    $(".igv" + supplier.value).html(igv.toFixed(2));
    total = amount + igv;
    $(".total" + supplier.value).html(total.toFixed(2));
  });
};

calcPriceEdit = function(event) {
  var amount, igv, supplier, total;
  if (this.value !== "") {
    supplier = this.value;
    amount = 0;
    $("input[name=edit" + supplier + "]").each(function(index, input) {
      amount += parseFloat(input.getAttribute("data-quantity")) * parseFloat(input.value);
    });
    $(".amountedit" + supplier).html(amount.toFixed(2));
    igv = amount * (parseFloat($("input[name=igv]").val()) / 100);
    $(".igvedit" + supplier).html(igv.toFixed(2));
    total = amount + igv;
    $(".totaledit" + supplier).html(total.toFixed(2));
    return;
  }
};

changeMaterials = function(event) {
  var val;
  if (this.checked) {
    val = Boolean(parseInt(this.value));
    $("input[name=mats]").each(function(index, element) {
      element.checked = val;
    });
  }
};

choicePrice = function() {
  var counter;
  counter = 0;
  $("input[name=mats]").each(function(index, element) {
    if (element.checked) {
      counter += 1;
    }
  });
  if (counter > 0) {
    $(".choice-price").modal("toggle");
    $(".btn-origin, .btn-edit").val(this.value);
  } else {
    $().toastmessage("showWarningToast", "Debe de seleccionar por lo menos un material para poder generar la orden de compra.");
  }
};
