// Generated by CoffeeScript 1.7.1
var calcPriceEdit, calcamounts, changeMaterials, choicePrice, savePurchase, showStepOne, showStepTwo;

$(document).ready(function() {
  $(".step-two").hide();
  $("[name=transfer]").datepicker({
    "showAnim": "slide",
    changeMonth: true,
    changeYear: true,
    dateFormat: "yy-mm-dd",
    minDate: "0"
  });
  $(".btn-refresh-price").on("click", calcPriceEdit);
  $("input[name=select]").on("change", changeMaterials);
  $(".btn-purchase").on("click", choicePrice);
  $(".btn-origin, .btn-edit").on("click", showStepTwo);
  $(".btn-back").on("click", showStepOne);
  $(".btn-save-purchase").on("click", savePurchase);
  $(".btn-show-deposit").click((function(_this) {
    return function(event) {
      $("[name=deposit]").click();
    };
  })(this));
  calcamounts();
});

calcamounts = function(event) {
  $("input[name=suppliers]").each(function(index, supplier) {
    var amount, igv, total;
    amount = 0;
    $("input[name=edit" + supplier.value + "]").each(function(index, input) {
      amount += parseFloat(input.getAttribute("data-amount"));
    });
    $(".amount" + supplier.value).html(amount.toFixed(2));
    igv = amount * (parseFloat($("input[name=igv]").val()) / 100);
    $(".igv" + supplier.value).html(igv.toFixed(2));
    total = amount + igv;
    $(".total" + supplier.value).html(total.toFixed(2));
  });
};

calcPriceEdit = function(event) {
  var amount, igv, supplier, total;
  if (this.value !== "") {
    supplier = this.value;
    amount = 0;
    $("input[name=edit" + supplier + "]").each(function(index, input) {
      amount += parseFloat(input.getAttribute("data-quantity")) * parseFloat(input.value);
    });
    $(".amountedit" + supplier).html(amount.toFixed(2));
    igv = amount * (parseFloat($("input[name=igv]").val()) / 100);
    $(".igvedit" + supplier).html(igv.toFixed(2));
    total = amount + igv;
    $(".totaledit" + supplier).html(total.toFixed(2));
    return;
  }
};

changeMaterials = function(event) {
  var val;
  if (this.checked) {
    val = Boolean(parseInt(this.value));
    $("input[name=mats]").each(function(index, element) {
      element.checked = val;
    });
  }
};

choicePrice = function() {
  var counter;
  counter = 0;
  $("input[name=mats]").each(function(index, element) {
    if (element.checked) {
      counter += 1;
    }
  });
  if (counter > 0) {
    $(".choice-price").modal("show");
    $(".btn-origin, .btn-edit").attr("data-s", this.value);
  } else {
    $().toastmessage("showWarningToast", "Debe de seleccionar por lo menos un material para poder generar la orden de compra.");
  }
};

showStepTwo = function(event) {
  $("input[name=prices]").val(this.value);
  $(".choice-price").modal("hide");
  $("[name=rucandreason]").html(this.getAttribute("data-s") + " - " + $(".get-reason-" + (this.getAttribute("data-s"))).text());
  $("[name=ruc]").val(this.getAttribute("data-s"));
  $("[name=reason]").val($(".get-reason-" + (this.getAttribute("data-s"))).text());
  $(".step-one").fadeOut(200);
  $(".step-two").fadeIn(800);
};

showStepOne = function(event) {
  $("input[name=prices]").val("");
  $(".step-two").fadeOut(200);
  $(".step-one").fadeIn(800);
};

savePurchase = function() {
  var $deposit, data, form, k, pass, v;
  form = new FormatData();
  data = new Object();
  data.proveedor = $("[name=ruc]").val();
  data.lugent = $("[name=delivery]").val();
  data.documento = $("[name=document]").val();
  data.pagos = $("[name=payment]").val();
  data.moneda = $("[name=currency]").val();
  data.traslado = $("[name=transfer]").val();
  data.contacto = $("[name=contact]").val();
  $deposit = $("[name=deposit]").get(0);
  pass = false;
  for (k in data) {
    v = data[k];
    if (v !== "") {
      form.append(k, v);
      pass = true;
    } else {
      pass = false;
      $().toastmessage("showWarningToast", "El campo " + k + " se encuentra vacio.");
      return pass;
    }
  }
  if (pass) {
    if ($deposit.files[0] !== null) {
      form.append("deposito", $deposit.files[0]);
    }
    form.append("save-purchase", true);
    $.ajax({
      url: "",
      type: "POST",
      data: form,
      dataType: "json",
      proccessData: false,
      cache: false,
      contentType: false,
      success: function(response) {
        if (response.status) {
          $().toastmessage("showWarningToast", "Felicidades! se a generar la <q>Orden de Compra</q> Nro " + response.purchase);
          return setTimeout(function() {
            return location.href = "/logistics/compare/quote/" + ($(".btn-kill").val()) + "/";
          }, 2600);
        } else {
          return $().toastmessage("showWErrorToast", "No se a podido generar la Orden de compra. Vuelva a intentarlo.");
        }
      }
    });
  }
};
