// Generated by CoffeeScript 1.8.0
var changeSelect, createTmpPurchase, createTmpQuatation, getListCheck;

$(document).ready(function() {
  $("input[name=select]").on("change", changeSelect);
  $("table.table-float").floatThead({
    useAbsolutePositioning: false,
    scrollingTop: 50
  });
});

changeSelect = function(event) {
  var radio;
  radio = this;
  if (this.checked) {
    $("input[name=materials]").each(function(index, element) {
      element.checked = Boolean(parseInt(radio.value));
    });
  }
};

getListCheck = function(event) {
  var data;
  data = new Array;
  $("input[name=materials]").each(function(index, element) {
    if (element.checked) {
      data.push({
        "materials": element.getAttribute("data-materials"),
        "quantity": element.value,
        "remainder": element.getAttribute("data-remainder"),
        "brand": element.getAttribute("data-brand"),
        "model": element.getAttribute("data-model")
      });
    }
  });
  if (data.length) {
    return data;
  }
};

createTmpQuatation = function(event) {
  var data;
  data = new Object;
  data.details = getListCheck();
  setTimeout(function() {
    if (data.details.length) {

    } else {
      return $().toastmessage("showWarningToast", "No se han encontrado materiales para cotizar.");
    }
  }, 300);
};

createTmpPurchase = function(event) {
  var data;
  data = new Object;
  data.details = getListCheck();
  setTimeout(function() {
    if (data.details.length) {

    } else {
      return $().toastmessage("showWarningToast", "No se han encontrado materiales para Comprar.");
    }
  }, 300);
};
