// Generated by CoffeeScript 1.7.1
var addNewMaterialPurchase, calcAmount, changeSearch, changeSelect, getDataPurchase, getSearch, listDetails, openWindow, showActions, showEditPurchasae, showPanelAdd, showStepOne;

$(document).ready(function() {
  $(".step-two, .panel-add").hide();
  $("input[name=star],input[name=end]").datepicker({
    dateFormat: "yy-mm-dd",
    showAnim: "slide"
  });
  $("input[name=search]").on("change", changeSearch);
  $(".btn-search").on("click", getSearch);
  $(document).on("click", ".btn-purchase", openWindow);
  $(document).on("click", ".btn-actions", showActions);
  $(".btn-edtp").on("click", showEditPurchasae);
  $(".btn-back").on("click", showStepOne);
  $("input[name=select]").on("change", changeSelect);
  $(".btn-show-add").on("mouseenter mouseleave", animateAdd).on("click", showPanelAdd);
});

changeSearch = function() {
  if (this.checked) {
    if (this.value === "status") {
      $("input[name=star],input[name=end],input[name=code]").attr("disabled", true);
      $("select[name=status]").attr("disabled", false);
      return;
    } else if (this.value === "dates") {
      $("input[name=star],input[name=end]").attr("disabled", false);
      $("select[name=status],input[name=code]").attr("disabled", true);
      return;
    } else if (this.value === "code") {
      $("input[name=star],input[name=end],select[name=status]").attr("disabled", true);
      $("input[name=code]").attr("disabled", false);
      return;
    }
  }
};

getSearch = function() {
  $("input[name=search]").each(function(index, element) {
    var data, end, start;
    if (element.checked) {
      data = new Object();
      if (element.value === "code") {
        if ($("input[name=code]").val() !== "") {
          data.code = $("input[name=code]").val();
          data.pass = true;
        } else {
          data.pass = false;
          $().toastmessage("showWarningToast", "campo de estado se encuntra vacio.");
        }
      } else if (element.value === "status") {
        if ($("select[name=status]").val() !== "") {
          data.status = $("select[name=status]").val();
          data.pass = true;
        } else {
          data.pass = false;
          $().toastmessage("showWarningToast", "campo de estado se encuntra vacio.");
        }
      } else if (element.value === "dates") {
        start = $("input[name=star]").val();
        if (start !== "") {
          data.dates = true;
          data.start = start;
          data.pass = true;
        } else {
          data.pass = false;
          $().toastmessage("showWarningToast", "campo de fecha inicio se encuntra vacio.");
        }
        end = $("input[name=end]").val();
        if (end !== "") {
          data.end = end;
        }
      }
      console.log(data);
      if (data.pass) {
        $.getJSON("", data, function(response) {
          var $tb, template, tmp, x;
          if (response.status) {
            template = "<tr> <td>{{ item }}</td> <td>{{ purchase }}</td> <td>{{ document }}</td> <td>{{ transfer }}</td> <td>{{ currency }}</td> <td><a class=\"text-black\" target=\"_blank\" href=\"/media/{{ deposito }}\"><span class=\"glyphicon glyphicon-file\"></span></a></td> <td><button value=\"{{ purchase }}\" class=\"btn btn-xs btn-link text-black btn-purchase\"><span class=\"glyphicon glyphicon-list\"></span></a> </td> <td> {{!status}} </td> </tr>";
            $tb = $("table > tbody");
            $tb.empty();
            for (x in response.list) {
              if (response.list[x].status === 'PE') {
                tmp = template.replace("{{!status}}", "<button class=\"btn btn-xs btn-link text-black btn-actions\" value=\"{{ purchase }}\"> <span class=\"glyphicon glyphicon-ok\"></span> </button>");
              } else {
                tmp = template;
              }
              response.list[x].item = parseInt(x) + 1;
              $tb.append(Mustache.render(tmp, response.list[x]));
            }
          }
        });
      }
    }
  });
};

openWindow = function() {
  window.open("/reports/order/purchase/" + this.value + "/", "_blank");
};

showActions = function(event) {
  $(".btn-delp,.btn-edtp").val(this.value);
  $(".mactions").modal("toggle");
};

showEditPurchasae = function(event) {
  $(".mactions").modal("hide");
  $(".nrop").text(this.value);
  getDataPurchase(this.value);
  $(".step-one").fadeOut(150);
  $(".step-two").fadeIn(800);
};

showStepOne = function(event) {
  $(".nrop").text("");
  $(".step-two").fadeOut(150);
  $(".step-one").fadeIn(800);
};

getDataPurchase = function(purchase) {
  var data;
  data = new Object;
  data.purchase = purchase;
  data.getpurchase = true;
  $.getJSON("", data, function(response) {
    var $tb, template, x;
    if (response.status) {
      $("[name=rucandreason]").text(response.reason);
      $("input[name=ruc]").val(response.supplier);
      $("input[name=reason]").val(response.reason);
      $("input[name=delivery]").val(response.space);
      $("select[name=document]").val(response.document);
      $("select[name=payment]").val(response.method);
      $("select[name=currency]").val(response.currency);
      $("input[name=transfer]").val(response.transfer);
      $("input[name=contact]").val(response.contact);
      $("input.edsct").val(response.discount);
      $("span.eigv").text("" + response.igv + "%");
      $tb = $("table.table-pod > tbody");
      $tb.empty();
      template = "<tr> <td> <input type=\"checkbox\" name=\"mats\" value=\"{{ materials }}\"> </td> <td>{{ item }}</td> <td>{{ materials }}</td> <td>{{ name }}</td> <td>{{ meter }}</td> <td>{{ unit }}</td> <td>{{ brand }}</td> <td>{{ model }}</td> <td>{{ quantity }}</td> <td>{{ price }}</td> <td>{{ discount }}</td> <td>{{ amount }}</td> <td> <button class=\"btn btn-xs btn-link text-green\"> <span class=\"glyphicon glyphicon-edit\"></span> </button> </td> </tr>";
      for (x in response.details) {
        response.details[x].item = parseInt(x) + 1;
        $tb.append(Mustache.render(template, response.details[x]));
      }
      calcAmount();
    } else {
      return $().toastmessage("showWarningToast", "No se han conseguidos los datos. " + response.raise);
    }
  });
};

calcAmount = function(event) {
  var amount, dsct, igv;
  amount = 0;
  $("table.table-pod > tbody > tr").each(function(index, element) {
    var $td;
    $td = $(element).find("td");
    amount += convertNumber($td.eq(11).text());
  });
  $(".tamount").text(amount.toFixed(2));
  dsct = (amount * convertNumber($("input.edsct").val())) / 100;
  $(".tdsct").text(dsct.toFixed(2));
  amount = amount - dsct;
  igv = $("span.eigv").text().split("%")[0];
  igv = amount * convertNumber(igv) / 100;
  $(".tigv").text(igv.toFixed(2));
  $(".ttotal").text((amount + igv).toFixed(2));
};

changeSelect = function(event) {
  $("input[name=select]").each(function(ind, radio) {
    if (this.checked) {
      $("input[name=mats]").each(function(index, element) {
        element.checked = Boolean(parseInt(radio.value));
      });
    }
  });
};

showPanelAdd = function(event) {
  var btn;
  btn = this;
  $(".panel-add").fadeToggle(600, function() {
    if (this.style.display === 'block') {
      $(btn).removeClass("btn-success text-black").addClass("btn-default").find("span").eq(0).removeClass("fa-plus-square-o").addClass("fa-times-circle-o");
      $(btn).find("span").eq(1).text("Cancelar");
    } else {
      $(btn).removeClass("btn-default").addClass("btn-success").addClass("text-black").find("span").eq(0).removeClass("fa-times-circle-o").addClass("fa-plus-square-o");
      $(btn).find("span").eq(1).text("Agregar Material");
    }
  });
};

addNewMaterialPurchase = function(event) {
  var data;
  data = new Object;
  data.code = $.trim($(".id-mat").text());
  if (data.code.length !== 15) {
    $().toastmessage("showWarningToast", "Seleccione por lo menos un material para ingresar.");
    return false;
  }
  data.quantity = convertNumber($("input[name=quantity]").val());
  if (isNaN(data.quantity) || data.quantity <= 0) {
    $().toastmessage("showWarningToast", "La cantidad ingresada debe ser mayor a 0.");
    return false;
  }
  data.price = convertNumber($("input[name=price]").val());
  if (isNaN(data.price) || data.quantity <= 0) {
    $().toastmessage("showWarningToast", "El precio ingresado debe ser mayor a 0.");
    return false;
  }
  data.brand = $("select[name=brand]").val();
  data.model = $("select[name=model]").val();
  if (data.brand !== "" && data.model !== "") {
    $().toastmessage("showWarningToast", "Debe de seleccionar una marca y modelo.");
    return false;
  }
  if ($("input[name=gincludegroup]").length && $("input[name=gincludegroup]").is(":checked")) {
    if (tmpObjectDetailsGroupMaterials.details.length) {
      data.details = tmpObjectDetailsGroupMaterials.details;
    }
  }
  data.csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val();
  $.post("", data, function(response) {
    if (response.status) {
      listDetails();
    }
  });
};

listDetails = function(event) {
  calcAmount();
};
