// Generated by CoffeeScript 1.7.1
var getDataProveedor, openSupplier;

$(document).ready(function() {
  $("select[name=proveedor]").on("click", getDataProveedor);
  $(".btn-default").on("click", openSupplier);
});

getDataProveedor = function() {
  var data;
  if (this.value !== "") {
    data = new Object();
    data.ruc = this.value;
    $.getJSON("", data, function(response) {
      if (response.status) {
        return $("input").attr("disabled", false);
      }
    });
  }
};

openSupplier = function() {
  var interval, url, win;
  url = "/logistics/crud/create/supplier/";
  win = window.open(url, "Popup", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=600");
  interval = window.setInterval(function() {
    if (win === null || win.closed) {
      window.clearInterval(interval);
      location.reload;
    }
  }, 1000);
  return win;
};
