// Generated by CoffeeScript 1.8.0
var selectProject;

$(document).ready(function() {
  $(".btn-erase-fields,.btn-generate").hide();
  $("input[name=start],input[name=execution]").datepicker({
    changeMonth: true,
    changeYear: true,
    closeText: "Cerrar",
    dateFormat: "yy-mm-dd",
    showAnim: "slide",
    showButtonPanel: true
  });
  $("select[name=project]").on("click", selectProject);
});

selectProject = function(event) {
  var $pro, data;
  $pro = $(this);
  if ($pro.val()) {
    data = new Object;
    data.pro = $pro.val();
    data.changeProject = true;
    $.getJSON("", data, function(response) {
      var $sub, tmp, x;
      if (response.status) {
        $sub = $("[name=subproject]");
        $sub.empty();
        if (response.subprojects) {
          tmp = "<option value=\"{{ id }}\">{{ x.subproject }}</option>";
          for (x in response.subprojects) {
            $sub.append(Mustache.render(tmp, response.subprojects[x]));
          }
        }
        $("input[name=arrival]").val(response.address);
      } else {
        $().toastmessage("showErrorToast", "No se a encontrado Proyectos. " + response.raise);
      }
    });
  }
};
