// Generated by CoffeeScript 1.7.1
(function() {
  var keyCode, keyDescription;

  $(document).ready(function() {
    $("input[name=description]").on("keyup", keyDescription);
    $("input[name=description]").on("keypress", keyUpDescription);
    $("select[name=meter]").on("click", getSummaryMaterials);
    $("input[name=code]").on("keypress", keyCode);
  });

  keyDescription = function(event) {
    var key;
    key = window.Event ? event.keyCode : event.which;
    if (key !== 13 && key !== 40 && key !== 38 && key !== 39 && key !== 37) {
      getDescription(this.value.toLowerCase());
    }
    if (key === 40 || key === 38 || key === 39 || key === 37) {
      moveTopBottom(key);
    }
  };

  keyCode = function(event) {
    var key;
    key = window.Event ? event.keyCode : event.which;
    if (key === 13) {
      return searchMaterialCode(this.value);
    }
  };

}).call(this);
