// Generated by CoffeeScript 1.7.1
var animateAdd;

animateAdd = function(event) {
  $(this).hover(function() {

    /*.removeClass "btn-success text-black"
    .addClass "btn-default"
     */
    $(this).find("span").eq(0).removeClass("fa-plus-square-0").addClass("fa-plus");

    /*$(@).find "span"
    .eq 1
    .text tfirst
     */
  }, function() {

    /*removeClass "btn-default"
    .addClass "btn-success text-black"
     */
    $(this).find("span").eq(0).removeClass("fa-plus").addClass("fa-plus-square-0");

    /*$(@).find "span"
    .eq 1
    .text tlast
     */
  });
};
