// Generated by CoffeeScript 1.7.1
var convertNumber, validateFormatDate;

validateFormatDate = function(data) {
  var RegExpattern, pass, value;
  value = data;
  pass = false;
  RegExpattern = /^\d{4}\-\d{1,2}\-\d{1,2}$/;
  if (value !== "" && value.match(RegExpattern)) {
    pass = true;
  }
  return pass;
};

convertNumber = function(val) {
  var num;
  if (isNaN(val)) {
    num = val.replace(",", ".");
    num = parseFloat(num);
  } else {
    num = parseFloat(val);
  }
  return num;
};
