from django.contrib import admin
from CMSGuias.apps.almacen import models

admin.site.register(models.Almacene)
admin.site.register(models.Cliente)
admin.site.register(models.Conductore)
admin.site.register(models.Departamento)
admin.site.register(models.Detpedido)
admin.site.register(models.Distrito)
admin.site.register(models.GuiaRemision)
admin.site.register(models.Materiale)
admin.site.register(models.Niple)
admin.site.register(models.Pais)
admin.site.register(models.Pedido)
admin.site.register(models.Provincia)
admin.site.register(models.Proyecto)
admin.site.register(models.Subproyecto)
admin.site.register(models.Sectore)
admin.site.register(models.Transportista)
admin.site.register(models.Transporte)
admin.site.register(models.Unidade)
admin.site.register(models.tmpniple)
admin.site.register(models.tmppedido)
admin.site.register(models.userProfile)