// Generated by CoffeeScript 1.7.1
var addMaterials, btnAddChangeIcon, listMaterials, showPanelAdd;

$(document).ready(function() {
  $(".panel-add-materials").hide();
  $(".btn-add-show").on("click", showPanelAdd);
  $(".btn-add").on("mouseenter mouseleave", btnAddChangeIcon);
  $("input[name=cantidad]").on("keydown", numberOnly);
  $("button.btn-add").on("click", addMaterials);
});

showPanelAdd = function(event) {
  var $btn;
  $btn = $(this);
  $(".panel-add-materials").fadeToggle(800, function() {
    if ($(this).is(":visible")) {
      $btn.removeClass("btn-success").removeClass("text-black").addClass("btn-default").find("span").eq(0).removeClass("glyphicon-plus-sign").addClass("glyphicon-remove-sign");
      $btn.find("span").eq(1).text("Cancelar");
    } else {
      $btn.removeClass("btn-default").addClass("btn-success").addClass("text-black").find("span").eq(0).removeClass("glyphicon-remove-sign").addClass("glyphicon-plus-sign");
      $btn.find("span").eq(1).text("Agregar");
    }
  });
};

btnAddChangeIcon = function(event) {
  $(this).hover(function() {
    $(this).find("span").eq(0).removeClass("glyphicon-plus-sign").addClass("glyphicon-plus");
  }, function() {
    $(this).find("span").eq(0).removeClass("glyphicon-plus").addClass("glyphicon-plus-sign");
  });
};

listMaterials = function(event) {
  var data;
  data = new Object;
  data.listMaterials = true;
  $.getJSON("", data, function(response) {
    var $tb, template, x, _results;
    if (response.status) {
      $tb = $("table.table-details > tbody");
      $tb.empty();
      template = "<tr class=\"tr{{ code }}\"> <td>{{ item }}</td> <td>{{ code }}</td> <td>{{ name }}</td> <td>{{ meter }}</td> <td>{{ unit }}</td> <td>{{ quantity }}</td> <td class=\"text-center\"> <button class=\"btn btn-xs btn-link text-green\" value=\"{{ code }}\"> <span class=\"glyphicon glyphicon-edit\"></span> </button> </td> <td class=\"text-center\"> <button class=\"btn btn-xs btn-link text-red\" value=\"{{ code }}\"> <span class=\"glyphicon glyphicon-trash\"></span> </button> </td> </tr>";
      _results = [];
      for (x in response.details) {
        response.details[x].item = parseInt(x) + 1;
        _results.push($tb.append(Mustache.render(template, response.details[x])));
      }
      return _results;
    }
  });
};

addMaterials = function(event) {
  var data;
  data = new Object;
  data.code = $(".id-mat").text();
  if (data.code === "") {
    $().toastmessage("showWarningToast", "Ingrese un material.");
    return false;
  }
  data.quantity = parseFloat($("input[name=cantidad]").val());
  if ($("input[name=cantidad]").val() === "") {
    return false;
    $().toastmessage("showWarningToast", "Ingrese una cantidad.");
  }
  data.csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val();
  data.addMaterials = true;
  $.post("", data, function(response) {
    if (response.status) {
      return listMaterials();
    } else {
      return $().toastmessage("showErrorToast", "No se a podido agregar el material. " + raise);
    }
  }, "json");
};
