// Generated by CoffeeScript 1.8.0
var addResultTable, searchCode, searchDesc, showEditMaterials, showNewMaterials;

$(document).ready(function() {
  $(".panel-new").hide();
  $("button.btn-top-page").on("click", goTopPage);
  $("input[name=searchCode]").on("keyup", searchCode);
  $("input[name=searchDesc]").on("keyup", searchDesc);
  $(document).on("click", "button[name=btnedit]", showEditMaterials);
  $("button.btn-show-new").on("click", showNewMaterials);
  $('table').floatThead({
    useAbsolutePositioning: false,
    scrollingTop: 50
  });
});

searchCode = function(event) {
  var data, key;
  key = event.keyCode || event.which;
  console.log(key);
  if (key === 13) {
    data = new Object;
    data.searchCode = true;
    data.code = $.trim(this.value);
    $.getJSON("", data, function(response) {
      if (response.status) {
        return addResultTable(response);
      }
    });
  }
};

searchDesc = function(event) {
  var data;
  data = new Object;
  data.searchDesc = true;
  data.desc = $.trim(this.value);
  $.getJSON("", data, function(response) {
    if (response.status) {
      return addResultTable(response);
    }
  });
};

addResultTable = function(response) {
  var $tb, template, x;
  template = "<tr> <td class=\"text-center\">{{ item }}</td> <td class=\"text-center\">{{ materials }}</td> <td>{{ name }}</td> <td>{{ measure }}</td> <td class=\"text-center\">{{ unit }}</td> <td>{{ finished }}</td> <td>{{ area }}</td> <td class=\"text-center\"> <button value=\"{{ materials }}\" data-des=\"{{ name }}\" data-met=\"{{ measure }}\" data-unit=\"{{ unit }}\" data-acb=\"{{ finished }}\" data-area=\"{{ area }}\" class=\"btn btn-xs btn-link text-black\" name=\"btnedit\"> <span class=\"fa fa-edit\"></span> </button> </td> <td value=\"{{ materials }}\" class=\"text-center\"> <button class=\"btn btn-xs btn-link text-red\" name=\"btndel\"> <span class=\"fa fa-trash-o\"></span> </button> </td> </tr>";
  $tb = $("table > tbody");
  $tb.empty();
  for (x in response.list) {
    response.list[x].item = parseInt(x) + 1;
    $tb.append(Mustache.render(template, response.list[x]));
  }
};

showNewMaterials = function(event) {
  var $btn;
  $btn = $(this);
  $(".panel-new").toggle("slow", function() {
    if (this.style.display === 'block') {
      $btn.removeClass("btn-primary").addClass("btn-default").find("span").eq(0).removeClass("fa-plus").addClass("fa-times");
      $btn.find("span").eq(1).text("Cancelar");
    } else {
      $btn.removeClass("btn-default").addClass("btn-primary").find("span").eq(0).removeClass("fa-times").addClass("fa-plus");
      $btn.find("span").eq(1).text("Numero Material");
    }
    return $('table').floatThead('reflow');
  });
};

showEditMaterials = function(event) {
  $("input[name=ematnom]").val(this.getAttribute("data-des"));
  $("input[name=ematmed]").val(this.getAttribute("data-met"));
  $("input[name=eunidad]").val(this.getAttribute("data-unit"));
  $("input[name=ematacb]").val(this.getAttribute("data-acb"));
  $("input[name=ematare]").val(this.getAttribute("data-area"));
  $(".meditmat").modal("show");
};
