// Generated by CoffeeScript 1.7.1
var showAuthenticateKeys;

$(document).ready(function() {
  $(".btn-show-key").on("click", showAuthenticateKeys);
});

showAuthenticateKeys = function() {
  $("[name=ruc]").val(this.getAttribute("data-ruc"));
  $("[name=quote]").val(this.getAttribute("data-quote"));
  $(".mkey").modal("toggle");
};
