// Generated by CoffeeScript 1.7.1
var calcTotals, saveBedside, saveBlurDigit, saveBlurString, showBedsideAfter, showBedsideBefore, showBrowser, uploadSheet, validMinandMax;

$(document).ready(function() {
  $(".bedside-after, .panel-bedside").hide();
  $("input[name=dates], input[name=traslado], input[name=validez]").datepicker({
    "minDate": "0",
    "dateFormat": "yy-mm-dd",
    "showAnim": "slide"
  });
  $(document).on("blur", "input[name=prices], input[name=desct]", saveBlurDigit);
  $(document).on("blur", "input[name=brands], input[name=models]", saveBlurString);
  $(document).on("change", "input[name=dates]", saveBlurString);
  $(".btn-file").on("click", showBrowser);
  $(document).on("change", "input[name=sheettech]", uploadSheet);
  calcTotals();
  $(".btn-show-bedside").on("click", showBedsideAfter);
  $(".btn-cancel").on("click", showBedsideBefore);
  $(".btn-send").on("click", saveBedside);
  tinymce.init({
    selector: "textarea[name=obser]",
    theme: "modern",
    menubar: false,
    statusbar: false,
    plugins: "link contextmenu fullscreen",
    fullpage_default_doctype: "<!DOCTYPE html>",
    font_size_style_values: "10px,12px,13px,14px,16px,18px,20px",
    toolbar1: "styleselect | fontsizeselect | fullscreen |",
    toolbar2: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |"
  });
  setTimeout(function() {
    return $(document).find("div#mceu_2").click(function(event) {
      if ($(this).attr("aria-pressed") === "false" || $(this).attr("aria-pressed") === void 0) {
        $(".navbar").hide();
      } else if ($(this).attr("aria-pressed") === "true") {
        $(".navbar").show();
      }
    });
  }, 2000);
});

validMinandMax = function(item) {
  if ($.trim(item.value) !== "") {
    if (parseFloat($.trim(item.value)) >= parseInt(item.getAttribute("min")) && parseFloat($.trim(item.value)) <= parseInt(item.getAttribute("max"))) {
      return true;
    } else {
      item.value = item.getAttribute("min");
      return false;
    }
  } else {
    item.value = item.getAttribute("min");
    return false;
  }
};

saveBlurDigit = function(event) {
  var btn, data;
  validMinandMax(this);
  if (!isNaN(parseFloat(this.value))) {
    btn = this;
    data = new Object();
    data.csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val();
    if (this.name === "prices") {
      data.blur = "price";
    } else if (this.name === "desct") {
      data.blur = "desct";
    }
    data.val = parseFloat(this.value);
    data.materials = this.getAttribute("data-mat");
    $.post("", data, function(response) {
      var $td, amount, discount, price, quantity;
      console.log(response);
      if (response.status) {
        $td = $("table > tbody > tr." + (btn.getAttribute("data-mat")) + " > td");
        quantity = response.quantity;
        if (data.blur === "desct") {
          price = parseFloat($td.eq(4).find("input").val());
          discount = parseFloat(data.val);
        } else {
          price = parseFloat(data.val);
          discount = parseFloat($td.eq(5).find("input").val() === "" ? 0 : $td.eq(5).find("input").val());
        }
        discount = price - ((price * discount) / 100);
        amount = quantity * discount;
        $td.eq(6).text(amount.toFixed(2));
        return calcTotals();
      }
    });
    return;
  }
};

calcTotals = function() {
  var amount, cigv, igv, totals;
  amount = 0;
  $("table > tbody > tr").each(function(index, element) {
    amount += parseFloat($(element).find("td").eq(6).text());
  });
  cigv = parseInt($("input[name=igv]").val());
  igv = (amount * cigv) / 100;
  totals = amount + igv;
  $(".subtc").text(amount.toFixed(2));
  $(".igvc").text(igv.toFixed(2));
  $(".totalc").text(totals.toFixed(2));
};

saveBlurString = function(event) {
  var data;
  console.log(this.value);
  if ($.trim(this.value) && $.trim(this.value) !== "None") {
    data = new Object();
    data.val = this.value;
    data.blur = this.name;
    data.materials = this.getAttribute("data-mat");
    data.csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val();
    $.post("", data);
  }
};

showBrowser = function(event) {
  $("input[name=sheettech]").click().attr("data-mat", this.value);
};

uploadSheet = function(event) {
  var data, input;
  if ($.trim(this.getAttribute("data-mat")) !== "" && this.files[0] !== null) {
    input = this;
    data = new FormData();
    data.append("type", "file");
    data.append("materials", this.getAttribute("data-mat"));
    data.append("sheet", this.files[0]);
    data.append("csrfmiddlewaretoken", $("input[name=csrfmiddlewaretoken]").val());
    $.ajax({
      url: "",
      data: data,
      type: "POST",
      dataType: "json",
      cache: false,
      contentType: false,
      processData: false,
      success: function(response) {
        var $file, clon;
        console.log(response);
        if (!response.status) {
          $().toastmessage("showWarningToast", "No se a podido cargar la hoja técnica. " + response.raise);
        }
        $file = $(input);
        $file.attr("data-mat", "");
        $file.val("");
        clon = $file.clone();
        return $file.replaceWith(clon);
      }
    });
  } else {
    this.setAttribute = "";
  }
};

showBedsideAfter = function(event) {
  $(".bedside-after, .panel-bedside").show(600);
  return $(".bedside-before").hide(200);
};

showBedsideBefore = function(event) {
  $(".bedside-after, .panel-bedside").hide(200);
  $(".bedside-before").show(600);
};

saveBedside = function(event) {
  var data;
  data = new Object();
  data.traslado = $("input[name=traslado]").val();
  data.validez = $("input[name=validez]").val();
  data.moneda = $("select[name=moneda]").val();
  data.contacto = $("input[name=contact]").val();
  data.obser = $("#obser_ifr").contents().find("body").html();
  if (data.traslado.length === 10 && data.traslado !== "" && data.validez.length === 10 && data.validez !== "" && data.moneda !== "") {
    data.csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val();
    data.client = true;
    $.post("", data, function(response) {
      if (response.status) {
        console.log(response);
        $().toastmessage("showNoticeToast", "Se ha guardado y enviado la cotización.");
        return setTimeout(function() {
          return location.href = "/proveedor/quote/";
        }, 2600);
      }
    });
    return;
  } else {
    $().toastmessage("showWarningToast", "Existe un campo vacio o con formato incorrecto, revise y vuelva a intentarlo.");
  }
};
