// Generated by CoffeeScript 1.7.1

/*$(document).ready ->
    $(".btn-primary").click signUp event
    return
 */

/*signUp = (event)->
    supplier = $("input[name=supplier]").val()
    username = $("input[name=username]").val()
    password = $("input[name=password]").val()
    if supplier is "" or username is "" or password is ""
        $().toastmessage "showWarningToast", "Campo Vacio"
        event.preventDefault()
        return false
    return
 */

