// Generated by CoffeeScript 1.8.0
var changeSearch, search;

$(document).ready(function() {
  $("input[name=sdate], input[name=edate]").datepicker({
    "showAnim": "slide",
    "dateFormat": "dd-mm-yy"
  });
  $("button.search").on("click", search);
  $("input[name=opsearch]").on("change", changeSearch);
});

changeSearch = function(event) {
  $(this).each(function() {
    if (this.checked) {
      if (this.value === "nro") {
        this.setAttribute("disabled", false);
        $("[name=status]").val('');
        $("[name=sdate], [name=edate]").val('');
      }
      if (this.value === "status") {
        $("[name=number]").val('');
        $("[name=sdate], [name=edate]").val('');
      }
      if (this.value === "date") {
        $("[name=number]").val('');
        return $("[name=status]").val('');
      }
    }
  });
};

search = function(event) {
  var $edate, $nro, $sdate, $status, context;
  $nro = $("input[name=number]");
  $status = $("select[name=status]");
  $sdate = $("input[name=sdate]");
  $edate = $("input[name=edate]");
  context = new Object;
  if ($nro.val().length === 10) {
    context.nro = $nro.val();
  }
  if ($status.val().length) {
    context.status = $status.val();
  }
  if ($sdate.val().length === 10) {
    context.sdate = $sdate.val();
  }
  if ($edate.val().length === 10) {
    context.edate = $edate.val();
  }
  if (Object.getOwnPropertyNames(context).length) {
    $.getJSON("", context, function(response) {
      var $table, template, x;
      if (response.status) {
        template = "<td class=\"text-center\">{{ item }}</td> <td>{{ ingress_id }}</td> <td>{{ purchase_id }}</td> <td>{{ invoice }}</td> <td>{{ register }}</td> <td>{{ status }}</td>";
        $table = $("table.table-noteingress > tbody");
        $table.empty();
        for (x in response.list) {
          response.list[x].item = parseInt(x) + 1;
          $table.append(Mustache.render(template, response.list[x]));
          return;
        }
      } else {
        $().toastmessage("showToastError", "No se a podido obtener datos. " + response.raise);
      }
    });
  }
};
