// Generated by CoffeeScript 1.7.1
(function() {
  var changeView, getSectors, openNewSector, openNewSubproyecto, openUpdateSector, openUpdateSubproject, openWindow, setSubproject;

  $(document).ready(function() {
    $(".new-sector").on("click", openNewSector);
    $(document).on("click", ".btn-edit-sector", openUpdateSector);
    $(".new-subproject").on("click", openNewSubproyecto);
    $(document).on("click", "#accordion > .panel-primary", setSubproject);
    $(document).on("click", ".btn-edit-sub", openUpdateSubproject);
    $(".btn-responsible").on("click", function() {
      return $(".mresponsible").modal("show");
    });
    $(".btn-files").on("click", function() {
      return $(".mfiles").modal("show");
    });
    $(".btn-cuadro").on("click", function(evetn) {
      return changeView(23);
    });
    $(".btn-list").on("click", function(event) {
      return changeView(100);
    });
    $(".btn-admin").on("click", function() {
      return $("[name=administrative]").click();
    });
    $(".btn-opera").on("click", function() {
      return $("[name=operation]").click();
    });
  });

  setSubproject = function(event) {
    console.log($(this).attr("data-sub"));
    $("input[name=sub]").val($(this).attr("data-sub"));
    if ($("input[name=sub]").val() !== "") {
      $(".header-project > .info-sub").remove();
      $(".header-project").append("<p class=\"info-sub\"><strong>Subproyecto :</strong> " + ($(".text-" + $(this).attr("data-sub")).html()) + " <strong> Codigo :</strong> " + ($(this).attr("data-sub")) + "</p>");
    } else {
      $("input[name=sub]").val();
      $(".header-project > .info-sub").remove();
    }
    getSectors();
  };

  getSectors = function() {
    var data, url;
    data = new Object();
    data.pro = $("input[name=pro]").val();
    data.sub = $("input[name=sub]").val();
    url = "/sales/projects/sectors/crud/";
    $.getJSON(url, data, function(response) {
      var $list, $sec, template, templist, x;
      console.log(response);
      if (response.status) {
        template = "<article> <button class=\"btn btn-xs text-black btn-link pull-left btn-edit-sector\" value=\"{{ sector_id }}\"> <span class=\"glyphicon glyphicon-pencil\"></span> </button> <button class=\"btn btn-xs text-black btn-link pull-right\" value=\"{{ sector_id }}\"> <span class=\"glyphicon glyphicon-trash\"></span> </button> <a href=\"\" class=\"text-black\"> {{ sector_id }} {{ nomsec }} <small>{{ planoid }}</small> </a> </article>";
        templist = "<li><a href=\"\" class=\"text-black\"><span class=\"glyphicon glyphicon-chevron-right\"></span> {{ nomsec }}</a></li>";
        $list = data['sub'] === "" ? $(".sectorsdefault") : $(".sectors" + data['sub']);
        console.log($list);
        $sec = $(".all-sectors");
        $sec.empty();
        $list.empty();
        for (x in response.list) {
          $sec.append(Mustache.render(template, response.list[x]));
          $list.append(Mustache.render(templist, response.list[x]));
        }
        equalheight(".all-sectors article");
      } else {
        return $().toastmessage("showErrorToast", "Error, transaction not complete. " + response.raise);
      }
    });
  };

  openNewSector = function(event) {
    var pro, sub, url;
    pro = $("input[name=pro]").val();
    sub = $("input[name=sub]").val();
    url = "/sales/projects/sectors/crud/?pro=" + pro + "&sub=" + sub + "&type=new";
    openWindow(url);
  };

  openUpdateSector = function(event) {
    var pro, sec, sub, url;
    pro = $("input[name=pro]").val();
    sub = $("input[name=sub]").val();
    sec = this.value;
    url = "/sales/projects/sectors/crud/?pro=" + pro + "&sub=" + sub + "&sec=" + sec + "&type=update";
    openWindow(url);
  };

  openNewSubproyecto = function(event) {
    var pro, url;
    pro = $("input[name=pro]").val();
    url = "/sales/projects/subprojects/crud/?pro=" + pro + "&type=new";
    openWindow(url);
  };

  openUpdateSubproject = function(event) {
    var pro, sub, url;
    pro = $("input[name=pro]").val();
    sub = this.value;
    url = "/sales/projects/subprojects/crud/?pro=" + pro + "&sub=" + sub + "&type=update";
    openWindow(url);
  };

  openWindow = function(url) {
    var interval, win;
    win = window.open(url, "Popup", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=600");
    interval = window.setInterval(function() {
      if (win === null || win.closed) {
        window.clearInterval(interval);
        getSectors();
      }
    }, 1000);
    return win;
  };

  changeView = function(percent) {
    $(".all-sectors > article").css({
      "width": "" + percent + "%"
    });
    equalheight(".all-sectors article");
  };

}).call(this);
