// Generated by CoffeeScript 1.7.1
(function() {
  var showaddProject;

  $(document).ready(function() {
    $(".btn-save, .panel-pro").hide();
    $(".btn-open > span").mouseenter(function(event) {
      event.preventDefault();
      $(this).removeClass("glyphicon-folder-close").addClass("glyphicon-folder-open");
    }).mouseout(function(event) {
      event.preventDefault();
      $(this).removeClass("glyphicon-folder-open").addClass("glyphicon-folder-close");
    });
    tinymce.init({
      selector: "textarea[name=obser]",
      theme: "modern",
      menubar: false,
      statusbar: false,
      plugins: "link contextmenu fullscreen",
      fullpage_default_doctype: "<!DOCTYPE html>",
      font_size_style_values: "10px,12px,13px,14px,16px,18px,20px",
      toolbar1: "styleselect | fontsizeselect | fullscreen |",
      toolbar2: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |"
    });
    setTimeout(function() {
      $(document).find("#mceu_2").click(function(event) {
        if ($(this).attr("aria-pressed") === "false" || $(this).attr("aria-pressed") === void 0) {
          $(".navbar").hide();
        } else if ($(this).attr("aria-pressed") === "true") {
          $(".navbar").show();
        }
      });
    }, 2000);
    $("[name=pais]").on("click", getDepartamentOption);
    $("[name=departamento]").on("click", getProvinceOption);
    $("[name=provincia]").on("click", getDistrictOption);
    $(".btn-country-refresh").on("click", getCountryOption);
    $(".btn-departament-refresh").on("click", getDepartamentOption);
    $(".btn-province-refresh").on("click", getProvinceOption);
    $(".btn-district-refresh").on("click", getDistrictOption);
    $(".btn-add").on("click", showaddProject);
  });

  showaddProject = function(event) {
    var $btn;
    event.preventDefault();
    $btn = $(this);
    $(".panel-pro").toggle(function() {
      if ($(this).is(":hidden")) {
        $btn.find("span").eq(0).removeClass("glyphicon-remove").addClass("glyphicon-plus");
        $btn.find("span").eq(1).html(" Nuevo Proyecto");
        $(".btn-save").hide();
      } else {
        $btn.find("span").eq(0).removeClass("glyphicon-plus").addClass("glyphicon-remove");
        $btn.find("span").eq(1).html(" Cancelar");
        $(".btn-save").show();
      }
    });
  };

}).call(this);
