// Generated by CoffeeScript 1.8.0
var CreateProject, deleteProject, openUpdateProject, openWindow, showCountry, showCustomer, showDepartament, showDistrict, showProvince, showaddProject;

$(document).ready(function() {
  $(".btn-save, .panel-pro").hide();
  $("input[name=comienzo], input[name=fin]").datepicker({
    "changeMonth": true,
    "changeYear": true,
    "showAnim": "slide",
    "dateFormat": "yy-mm-dd"
  });
  $(".btn-open > span").mouseenter(function(event) {
    event.preventDefault();
    $(this).removeClass("glyphicon-folder-close").addClass("glyphicon-folder-open");
  }).mouseout(function(event) {
    $(this).removeClass("glyphicon-folder-open").addClass("glyphicon-folder-close");
  });
  $("table").floatThead({
    useAbsolutePositioning: false,
    scrollingTop: 50
  });
  tinymce.init({
    selector: "textarea[name=obser]",
    theme: "modern",
    menubar: false,
    statusbar: false,
    plugins: "link contextmenu fullscreen",
    fullpage_default_doctype: "<!DOCTYPE html>",
    font_size_style_values: "10px,12px,13px,14px,16px,18px,20px",
    toolbar1: "styleselect | fontsizeselect | fullscreen |",
    toolbar2: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent |"
  });
  setTimeout(function() {
    $(document).find("#mceu_2").click(function(event) {
      if ($(this).attr("aria-pressed") === "false" || $(this).attr("aria-pressed") === void 0) {
        $(".navbar").hide();
      } else if ($(this).attr("aria-pressed") === "true") {
        $(".navbar").show();
      }
    });
    $(".btn-add").on("click", showaddProject);
    $("[name=pais]").on("click", getDepartamentOption);
    $("[name=departamento]").on("click", getProvinceOption);
    $("[name=provincia]").on("click", getDistrictOption);
    $(".btn-country-refresh").on("click", getCountryOption);
    $(".btn-departament-refresh").on("click", getDepartamentOption);
    $(".btn-province-refresh").on("click", getProvinceOption);
    $(".btn-district-refresh").on("click", getDistrictOption);
    $(".btn-add-customers").on("click", showCustomer);
    $(".btn-add-country").on("click", showCountry);
    $(".btn-add-departament").on("click", showDepartament);
    $(".btn-add-province").on("click", showProvince);
    $(".btn-add-district").on("click", showDistrict);
    $(".btn-save").on("click", CreateProject);
    $(".btn-show-edit").on("click", openUpdateProject);
    $(".btn-show-delete").on("click", deleteProject);
  }, 2000);
});

showaddProject = function(event) {
  var $btn;
  $btn = $(this);
  $(".panel-pro").toggle(function() {
    if ($(this).is(":hidden")) {
      $btn.find("span").eq(0).removeClass("glyphicon-remove").addClass("glyphicon-plus");
      $btn.find("span").eq(1).html(" Nuevo Proyecto");
      $(".btn-save").hide();
    } else {
      $btn.find("span").eq(0).removeClass("glyphicon-plus").addClass("glyphicon-remove");
      $btn.find("span").eq(1).html(" Cancelar");
      $(".btn-save").show();
    }
    return $("table").floatThead("reflow");
  });
};

showCustomer = function(event) {
  var url;
  event.preventDefault();
  url = "/customers/new/";
  return window.open(url, "Customers", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=600");
};

showCountry = function(event) {
  var url;
  event.preventDefault();
  url = "/country/new/";
  return window.open(url, "Country", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=500");
};

showDepartament = function(event) {
  var url;
  event.preventDefault();
  url = "/departament/new/";
  return window.open(url, "Departament", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=500");
};

showProvince = function(event) {
  var url;
  event.preventDefault();
  url = "/province/new/";
  return window.open(url, "Province", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=500");
};

showDistrict = function(event) {
  var url;
  event.preventDefault();
  url = "/district/new/";
  return window.open(url, "District", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=500");
};

CreateProject = function(event) {
  var data, pass;
  pass = false;
  data = new Object();
  $(".panel-pro").find("input, select").each(function() {
    if (this.value === "" || this.value === null) {
      console.log(this.name);
      this.focus();
      pass = false;
      $().toastmessage("showWarningToast", "campo vacio " + this.name + ".");
      return pass;
    } else {
      data[this.name] = $(this).val();
      pass = true;
    }
  });
  if (pass) {
    data['obser'] = $("#obser_ifr").contents().find("body").html();
    data['type'] = "new";
    $.post("", data, function(response) {
      if (response.status) {
        $().toastmessage("showNoticeToast", "Se registro el proyecto " + data['nompro'] + " correctamente!");
        return setTimeout(function() {
          return location.reload();
        }, 2000);
      } else {
        return $().toastmessage("showErrorToast", "Error en la transacción " + response.raise + ".");
      }
    });
    return;
  }
};

openUpdateProject = function(event) {
  var pro, url;
  pro = this.value;
  url = "/almacen/keep/project/" + pro + "/edit/";
  openWindow(url);
};

openWindow = function(url) {
  var interval, win;
  win = window.open(url, "Popup", "toolbar=no, scrollbars=yes, resizable=no, width=400, height=600");
  interval = window.setInterval(function() {
    if (win === null || win.closed) {
      window.clearInterval(interval);
      location.reload;
    }
  }, 1000);
  return win;
};

deleteProject = function() {
  var value;
  value = this.value;
  return $().toastmessage("showToast", {
    text: "Eliminar Proyecto, recuerde que al eliminar a " + this.title + " sera permanentemente.<br>Desea Eliminar el Proyecto?",
    sticky: true,
    type: "confirm",
    position: "middle-center",
    buttons: [
      {
        value: 'No'
      }, {
        value: 'Si'
      }
    ],
    success: function(result) {
      var data;
      if (result === "Si") {
        data = {
          "proid": value,
          "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val()
        };
        return $.post("/almacen/keep/project/", data, function(response) {
          if (response.status) {
            if ($("table tbody > tr").length > 1) {
              return $(".tr-" + value).remove();
            } else {
              return location.reload();
            }
          }
        }, "json");
      }
    }
  });
};
