// Generated by CoffeeScript 1.8.0
var getMaterialsAll, getmeasure, getsummary;

$(document).ready(function() {
  getMaterialsAll();
  $("[name=materials], [name=measure]").chosen({
    width: "100%"
  });
  $("[name=materials]").on("change", getmeasure);
  $("[name=measure]").on("change", getsummary);
});

getMaterialsAll = function(event) {
  var context;
  context = new Object();
  context.searchName = true;
  context.name = '';
  $.getJSON("/materials/", context, function(response) {
    var $op, template;
    if (response.status) {
      $op = $("[name=materials]");
      $op.empty();
      template = "{{#names}}<option value=\"{{ name }}\">{{ name }}</option>{{/names}}";
      $op.html(Mustache.render(template, response));
      return $op.trigger("chosen:updated");
    }
  });
};

getmeasure = function(event) {
  var context;
  context = new Object;
  context.searchMeter = true;
  context.name = this.value;
  $.getJSON("/materials/", context, function(response) {
    var $se, template;
    if (response.status) {
      $se = $("[name=measure]");
      $se.empty();
      $se.append("<option></option>");
      template = "{{#meter}} <option value=\"{{code}}\">{{measure}}</option> {{/meter}}";
      $se.html(Mustache.render(template, response));
      return $se.trigger("chosen:updated");
    }
  });
};

getsummary = function(event) {
  var context;
  context = new Object;
  context.scode = $("[name=measure]").val();
  context.summary = true;
  if (context.scode.length === 15) {
    $.getJSON("/materials/", context, function(response) {
      var $s, template;
      if (response.status) {
        template = "<table class=\"table table-condensed\"> <tbody> <tr> <th>Código</th> <td>{{ summary.materiales_id }}</td> </tr> <tr> <th>Nombre</th> <td>{{ summary.matnom }}</td> </tr> <tr> <th>Unidad</th> <td>{{ summary.unidad__uninom }}</td> </tr> </tbody> </table>";
        $s = $("[name=summary]");
        $s.empty();
        $s.html(Mustache.render(template, response));
      }
    });
  } else {
    $().toastmessage("showWarningToast", "El código del material no es valido.");
  }
};
